version: '3.8'
services:
  my_nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    links:
      - my_php
  my_php:
    build:
      dockerfile: docker/php/Dockerfile
      context: .
    volumes:
      - .:/var/www/html






